// <auto-generated />
namespace Movie_Recommendation_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cinemaShowtimedatevalidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cinemaShowtimedatevalidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201912210954470_cinemaShowtime-date-validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
