// <auto-generated />
namespace Movie_Recommendation_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class validationaddedforallmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validationaddedforallmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201912250854003_validation-added-for-all-models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
